// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/23/2025, 5:05:50 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/andrewchakdahah/Documents/website/ingen-cloud-tech/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/andrewchakdahah/Documents/website/ingen-cloud-tech/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/andrewchakdahah/Documents/website/ingen-cloud-tech/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/andrewchakdahah/Documents/website/ingen-cloud-tech/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/andrewchakdahah/Documents/website/ingen-cloud-tech/plugins/**/*.{js,ts,mjs}","/Users/andrewchakdahah/Documents/website/ingen-cloud-tech/composables/**/*.{js,ts,mjs}","/Users/andrewchakdahah/Documents/website/ingen-cloud-tech/utils/**/*.{js,ts,mjs}","/Users/andrewchakdahah/Documents/website/ingen-cloud-tech/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/andrewchakdahah/Documents/website/ingen-cloud-tech/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/andrewchakdahah/Documents/website/ingen-cloud-tech/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/andrewchakdahah/Documents/website/ingen-cloud-tech/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["content"]["files"]["18"] = "/Users/andrewchakdahah/Documents/website/ingen-cloud-tech/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})();

export default resolvedConfig;